
package com.making.cp.cliente.notificacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificacionService", targetNamespace = "http://services.ecos.edu.uniandes.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificacionService {


    /**
     * 
     * @param codigoEstado
     * @param codigoCiudadano
     * @return
     *     returns com.making.cp.cliente.notificacion.RespuestaNotificacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerNotificacionCiudadanoEstado", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.ObtenerNotificacionCiudadanoEstado")
    @ResponseWrapper(localName = "obtenerNotificacionCiudadanoEstadoResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.ObtenerNotificacionCiudadanoEstadoResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/NotificacionService/obtenerNotificacionCiudadanoEstadoRequest", output = "http://services.ecos.edu.uniandes.co/NotificacionService/obtenerNotificacionCiudadanoEstadoResponse")
    public RespuestaNotificacion obtenerNotificacionCiudadanoEstado(
        @WebParam(name = "codigoCiudadano", targetNamespace = "")
        Integer codigoCiudadano,
        @WebParam(name = "codigoEstado", targetNamespace = "")
        Integer codigoEstado);

    /**
     * 
     * @param codigoCiudadano
     * @return
     *     returns com.making.cp.cliente.notificacion.RespuestaNotificacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerNotificacionCiudadano", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.ObtenerNotificacionCiudadano")
    @ResponseWrapper(localName = "obtenerNotificacionCiudadanoResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.ObtenerNotificacionCiudadanoResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/NotificacionService/obtenerNotificacionCiudadanoRequest", output = "http://services.ecos.edu.uniandes.co/NotificacionService/obtenerNotificacionCiudadanoResponse")
    public RespuestaNotificacion obtenerNotificacionCiudadano(
        @WebParam(name = "codigoCiudadano", targetNamespace = "")
        Integer codigoCiudadano);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.making.cp.cliente.notificacion.RespuestaService
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cambiarEstadoNotificacion", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.CambiarEstadoNotificacion")
    @ResponseWrapper(localName = "cambiarEstadoNotificacionResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.CambiarEstadoNotificacionResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/NotificacionService/cambiarEstadoNotificacionRequest", output = "http://services.ecos.edu.uniandes.co/NotificacionService/cambiarEstadoNotificacionResponse")
    public RespuestaService cambiarEstadoNotificacion(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns com.making.cp.cliente.notificacion.RespuestaNotificacionEstado
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerNotificacionEstados", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.ObtenerNotificacionEstados")
    @ResponseWrapper(localName = "obtenerNotificacionEstadosResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.ObtenerNotificacionEstadosResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/NotificacionService/obtenerNotificacionEstadosRequest", output = "http://services.ecos.edu.uniandes.co/NotificacionService/obtenerNotificacionEstadosResponse")
    public RespuestaNotificacionEstado obtenerNotificacionEstados();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.making.cp.cliente.notificacion.RespuestaService
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "asignarNotificacion", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.AsignarNotificacion")
    @ResponseWrapper(localName = "asignarNotificacionResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.notificacion.AsignarNotificacionResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/NotificacionService/asignarNotificacionRequest", output = "http://services.ecos.edu.uniandes.co/NotificacionService/asignarNotificacionResponse")
    public RespuestaService asignarNotificacion(
        @WebParam(name = "arg0", targetNamespace = "")
        NotificacionDto arg0);

}
