
package com.making.cp.cliente.emisor;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EmisorService", targetNamespace = "http://services.ecos.edu.uniandes.co/")
public interface EmisorService {


    /**
     * 
     * @return
     *     returns com.making.cp.cliente.RespuestaEmisor
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerEmisores", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ObtenerEmisores")
    @ResponseWrapper(localName = "obtenerEmisoresResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ObtenerEmisoresResponse")
    public RespuestaEmisor obtenerEmisores();

}
