
package com.making.co.cliente.ciudadano;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CiudadanoService", targetNamespace = "http://services.ecos.edu.uniandes.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CiudadanoService {


    /**
     * 
     * @param identificacionOperador
     * @param ciudadano
     * @return
     *     returns com.making.cp.cliente.ciudadano.RespuestaService
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearCiudadano", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.CrearCiudadano")
    @ResponseWrapper(localName = "crearCiudadanoResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.CrearCiudadanoResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/CiudadanoService/crearCiudadanoRequest", output = "http://services.ecos.edu.uniandes.co/CiudadanoService/crearCiudadanoResponse")
    public RespuestaService crearCiudadano(
        @WebParam(name = "identificacionOperador", targetNamespace = "")
        String identificacionOperador,
        @WebParam(name = "ciudadano", targetNamespace = "")
        CiudadanoDto ciudadano);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.HelloResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/CiudadanoService/helloRequest", output = "http://services.ecos.edu.uniandes.co/CiudadanoService/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param codigoIdentificador
     * @param identificacionOperador
     * @return
     *     returns com.making.cp.cliente.ciudadano.RespuestaCiudadano
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerCiudadanoPorCodigoIdentificador", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.ObtenerCiudadanoPorCodigoIdentificador")
    @ResponseWrapper(localName = "obtenerCiudadanoPorCodigoIdentificadorResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.ObtenerCiudadanoPorCodigoIdentificadorResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/CiudadanoService/obtenerCiudadanoPorCodigoIdentificadorRequest", output = "http://services.ecos.edu.uniandes.co/CiudadanoService/obtenerCiudadanoPorCodigoIdentificadorResponse")
    public RespuestaCiudadano obtenerCiudadanoPorCodigoIdentificador(
        @WebParam(name = "identificacionOperador", targetNamespace = "")
        String identificacionOperador,
        @WebParam(name = "codigoIdentificador", targetNamespace = "")
        int codigoIdentificador);

    /**
     * 
     * @param identificacionOperador
     * @param identificacion
     * @param tipoIdentifiacion
     * @return
     *     returns com.making.cp.cliente.ciudadano.RespuestaCiudadano
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuarioPorIdentificacionYTipoDeIdentificacion", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.ObtenerUsuarioPorIdentificacionYTipoDeIdentificacion")
    @ResponseWrapper(localName = "obtenerUsuarioPorIdentificacionYTipoDeIdentificacionResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.ObtenerUsuarioPorIdentificacionYTipoDeIdentificacionResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/CiudadanoService/obtenerUsuarioPorIdentificacionYTipoDeIdentificacionRequest", output = "http://services.ecos.edu.uniandes.co/CiudadanoService/obtenerUsuarioPorIdentificacionYTipoDeIdentificacionResponse")
    public RespuestaCiudadano obtenerUsuarioPorIdentificacionYTipoDeIdentificacion(
        @WebParam(name = "identificacionOperador", targetNamespace = "")
        String identificacionOperador,
        @WebParam(name = "identificacion", targetNamespace = "")
        String identificacion,
        @WebParam(name = "tipoIdentifiacion", targetNamespace = "")
        int tipoIdentifiacion);

    /**
     * 
     * @param identificacionOperador
     * @param ciudadano
     * @return
     *     returns com.making.cp.cliente.ciudadano.RespuestaService
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarCiudadano", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.ActualizarCiudadano")
    @ResponseWrapper(localName = "actualizarCiudadanoResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.ActualizarCiudadanoResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/CiudadanoService/actualizarCiudadanoRequest", output = "http://services.ecos.edu.uniandes.co/CiudadanoService/actualizarCiudadanoResponse")
    public RespuestaService actualizarCiudadano(
        @WebParam(name = "identificacionOperador", targetNamespace = "")
        String identificacionOperador,
        @WebParam(name = "ciudadano", targetNamespace = "")
        CiudadanoDto ciudadano);

    /**
     * 
     * @return
     *     returns com.making.cp.cliente.ciudadano.RespuestaTipoIdentificacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTiposIdentificacion", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.ObtenerTiposIdentificacion")
    @ResponseWrapper(localName = "obtenerTiposIdentificacionResponse", targetNamespace = "http://services.ecos.edu.uniandes.co/", className = "com.making.cp.cliente.ciudadano.ObtenerTiposIdentificacionResponse")
    @Action(input = "http://services.ecos.edu.uniandes.co/CiudadanoService/obtenerTiposIdentificacionRequest", output = "http://services.ecos.edu.uniandes.co/CiudadanoService/obtenerTiposIdentificacionResponse")
    public RespuestaTipoIdentificacion obtenerTiposIdentificacion();

}
