
package com.making.co.cliente.ciudadano;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CiudadanoService", targetNamespace = "http://services.ecos.edu.uniandes.co/", wsdlLocation = "http://MacBook-Pro-de-Camilo.local:8080/projectCentralizador-web/CiudadanoService?wsdl")
public class CiudadanoService_Service
    extends Service
{

    private final static URL CIUDADANOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CIUDADANOSERVICE_EXCEPTION;
    private final static QName CIUDADANOSERVICE_QNAME = new QName("http://services.ecos.edu.uniandes.co/", "CiudadanoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://MacBook-Pro-de-Camilo.local:8080/projectCentralizador-web/CiudadanoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CIUDADANOSERVICE_WSDL_LOCATION = url;
        CIUDADANOSERVICE_EXCEPTION = e;
    }

    public CiudadanoService_Service() {
        super(__getWsdlLocation(), CIUDADANOSERVICE_QNAME);
    }

    public CiudadanoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CIUDADANOSERVICE_QNAME, features);
    }

    public CiudadanoService_Service(URL wsdlLocation) {
        super(wsdlLocation, CIUDADANOSERVICE_QNAME);
    }

    public CiudadanoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CIUDADANOSERVICE_QNAME, features);
    }

    public CiudadanoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CiudadanoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CiudadanoService
     */
    @WebEndpoint(name = "CiudadanoServicePort")
    public CiudadanoService getCiudadanoServicePort() {
        return super.getPort(new QName("http://services.ecos.edu.uniandes.co/", "CiudadanoServicePort"), CiudadanoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CiudadanoService
     */
    @WebEndpoint(name = "CiudadanoServicePort")
    public CiudadanoService getCiudadanoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ecos.edu.uniandes.co/", "CiudadanoServicePort"), CiudadanoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CIUDADANOSERVICE_EXCEPTION!= null) {
            throw CIUDADANOSERVICE_EXCEPTION;
        }
        return CIUDADANOSERVICE_WSDL_LOCATION;
    }

}
